### ISSUE TITLE
Jt copy

### ISSUE THREAD

**Issue by gautam-y** [gautam-y/Ansible#10]
```

```yaml
---
- name: Manage files on node1 and transfer to node2
  hosts: node1
  tasks:
    - name: Create a file on node1
      ansible.builtin.file:
        path: /tmp/myfile.txt
        state: touch

    - name: Move file to another directory on node1
      ansible.builtin.command:
        cmd: mv /tmp/myfile.txt /tmp/new_directory/myfile.txt

- name: Transfer file from node1 to node2
  hosts: node2
  tasks:
    - name: Copy file from node1 to node2
      ansible.builtin.fetch:
        src: /tmp/new_directory/myfile.txt
        dest: /tmp/
        flat: yes

```

```
