### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by gautam-y** [gautam-y/Ansible#5]

**Comment by gautam-y** [comment]
---
- name: Clone repo, add test file, and push changes
  hosts: localhost
  vars:
    repo_url: "https://github.com/username/repo.git"
    repo_dest: "/path/to/repo"
    test_file: "test_file.txt"
    test_content: "This is a test file."
    commit_message: "Add test file"
    git_username: "your_github_username"
    git_password: "your_github_password"
    http_proxy: "http://proxy.example.com:8080"
    https_proxy: "http://proxy.example.com:8080"
  tasks:
    - name: Set proxy environment variables
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "localhost,127.0.0.1"

    - name: Clone the Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        clone: yes
        update: yes
        version: 'master'
        force: yes

    - name: Add, commit, and push changes in one command
      shell: |
        echo "{{ test_content }}" > "{{ repo_dest }}/{{ test_file }}"
        cd "{{ repo_dest }}"
        git add .
        git commit -m "{{ commit_message }}"
        git push
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "localhost,127.0.0.1"

**Comment by gautam-y** [comment]
```yaml
---
- hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/your-username/your-repo.git"
    repo_dir: "/path/to/repo"
    proxy_url: "http://proxy.example.com:8080"
    proxy_env:
      http_proxy: "{{ proxy_url }}"
      https_proxy: "{{ proxy_url }}"

  tasks:

    - name: Install required packages
      apt:
        name:
          - git
        state: present
        update_cache: yes

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        force: yes
      environment: "{{ proxy_env }}"

    - name: Create a new file
      copy:
        content: "This is a test file created by Ansible"
        dest: "{{ repo_dir }}/test.txt"

    - name: Add new file to Git
      command: git add test.txt
      args:
        chdir: "{{ repo_dir }}"

    - name: Commit changes
      command: git commit -m "Added test file"
      args:
        chdir: "{{ repo_dir }}"

    - name: Push changes to remote
      command: git push
      args:
        chdir: "{{ repo_dir }}"
      environment: "{{ proxy_env }}"

```
